theme = 'nostyleplease'
baseURL = 'https://danlamanna.com/'
languageCode = 'en-us'
title = 'dan lamanna'

[params]
  [params.theme_config]
    back_home_text = "home"


[markup]
  [markup.highlight]
    style = 'doom-one2'
